version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${CI_COMMIT_SHA}
    image: frontend_web
    ports:
      - 80:80
    restart: unless-stopped